
starter = ["plains", "mountains", "ocean", "arctic", "ocean"]

[elements]
  [elements.plains]
  Name = "Plains"
  description = "Plains"
  size = 5

  [elements.mountains]
  Name = "Mountains"
  description = "Mountains"
  size = 5

  [elements.rivers]
  Name = "Rivers"
  description = "Rivers"
  combos = ["storms+mountains"]
  size = 1

  [elements.ocean]
  Name = "Ocean"
  description = "Ocean"
  size = 5

  [elements.arctic]
  Name = "Arctic"
  description = "Arctic wasteland of ice"
  size = 5

  [elements.storms]
  Name = "Storms"
  description = "Storms"
  size = 3
  combos = ["ocean"]
